<?php
/**
 * Demo map markers (no Google API). Used when no DB coordinates exist,
 * and for the homepage sample map preview. Coordinates are approximate
 * around Addalaichenai / Oluvil for layout only — replace via admin when ready.
 */
return [
    [
        'id' => null,
        'name' => 'Sample: Oluvil coastal walk',
        'address' => 'Oluvil area (placeholder)',
        'latitude' => 7.2835,
        'longitude' => 81.8520,
        'short_description' => 'Demo marker for a scenic coastal stretch. Replace with a real attraction in admin.',
        'description' => 'This is a placeholder pin for your project demo. Add latitude and longitude to real attractions to replace this preview.',
        'image' => '',
        'category_name' => 'Sample preview',
        'opening_hours' => 'Demo only',
        'contact_info' => '—',
        'distance_km' => '—',
    ],
    [
        'id' => null,
        'name' => 'Sample: Addalaichenai town centre',
        'address' => 'Addalaichenai (placeholder)',
        'latitude' => 7.2525,
        'longitude' => 81.8635,
        'short_description' => 'Demo marker for the main town hub, shops, and local life.',
        'description' => 'Placeholder content. Your live listings will appear here once each place has coordinates saved.',
        'image' => '',
        'category_name' => 'Sample preview',
        'opening_hours' => 'Demo only',
        'contact_info' => '—',
        'distance_km' => '—',
    ],
    [
        'id' => null,
        'name' => 'Sample: Harbour viewpoint',
        'address' => 'Oluvil Harbour area (placeholder)',
        'latitude' => 7.2760,
        'longitude' => 81.8668,
        'short_description' => 'Demo marker for harbour activity and sea views.',
        'description' => 'Use the full Map page after adding real data to explore actual pins and attraction pages.',
        'image' => '',
        'category_name' => 'Sample preview',
        'opening_hours' => 'Demo only',
        'contact_info' => '—',
        'distance_km' => '—',
    ],
    [
        'id' => null,
        'name' => 'Sample: Lagoon & wetlands',
        'address' => 'Eastern Province (placeholder)',
        'latitude' => 7.2680,
        'longitude' => 81.8580,
        'short_description' => 'Demo marker for nature and birdwatching style stops.',
        'description' => 'TripZo uses OpenStreetMap tiles only — no Google Maps API required.',
        'image' => '',
        'category_name' => 'Sample preview',
        'opening_hours' => 'Demo only',
        'contact_info' => '—',
        'distance_km' => '—',
    ],
    [
        'id' => null,
        'name' => 'Sample: Regional day-trip hub',
        'address' => 'Akkaraipattu area (placeholder)',
        'latitude' => 7.2140,
        'longitude' => 81.8482,
        'short_description' => 'Demo marker for a secondary hub on a longer route.',
        'description' => 'Markers numbered 1–5 are for presentation. Admin-added attractions will use real photos and detail pages.',
        'image' => '',
        'category_name' => 'Sample preview',
        'opening_hours' => 'Demo only',
        'contact_info' => '—',
        'distance_km' => '—',
    ],
];
